# Lesson 2 Practice: NumPy Part 2
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L02-Numpy_Part2-Lesson.ipynb](./L02-Numpy_Part2-Lesson.ipynb).  


## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired. 

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [1]:
import numpy as np

## Task 2a: Indexing by Subsetting and Slicing

In the practice notebook perform the following:

1. Create (or re-use) 3 arrays, each containing three dimensions.
2. Slice each of these arrays so that:
    + One element / number is returned.
    + One dimension is returned.
    + A subset of a dimension is returned.
3. What is the difference between `[x:]` and `[x, ...]`? (hint, try each on high-dimension arrays).
    
*Exactly what you choose to return is not imporant at this point, the goal of this task is to train you so that if you are given an n-dimension NumPy array, you can write an index or slice that returns a subset of desired positions.*

In [3]:
# Create three 3-D arrays
array1 = np.random.random((2,4,5))
array2 = np.random.random((2,2,2))
array3 = np.random.random((3,2,4))

# Slice each of these arrays so that 
# One element/number is returned
array1[-1, -1, -1]
array2[0,0,0]
array3[0,1,0]

# One dimension is returned
array1[-1, -1]
array2[0, 0]


# a subset of a dimension is returned 
array3[1:2, 0]


# What is the difference between [x:] and [x, ...] 
array3[1:3]
array3[2,1]

# The difference is that [x:] is subsetting within each axis and [x, ...] is subsetting each axis 

array([0.90134695, 0.23346947, 0.37984299, 0.90220974])

## Task 3a: Boolean Indexing

In the practice notebook perform the following:

+ Experiment with the following boolean conditionals to generate boolean arrays for indexing:
  + Greater than
  + Less than
  + Equals
  + Combine two or more of the above with:
      + or `|`
      + and `&`

You can create arrays or use existing ones

In [4]:

array1[array1 < 0.5]

array2[array2 > 0.25]

array3 == 0.5

array1 < 0.25 | array1 > 0.75


TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

## Task 4a: Getting Help

In the practice notebook perform the following:

+ In the code cell below, call `help()` on two of the following functions: `np.transpose()`, `np.reshape()`, `np.resize()`, `np.ravel()`, `np.append()`, `np.delete()`, `np.concatenate()`, `np.vstack()`, `np.hstack()`, `np.column_stack()`, `np.vsplit()`, `np.hsplit()` 
+ Respond to this question: Did you understand the help docuemntation? Could you use the function just by looking at what the help says about it?  

In [10]:
help(np.transpose)
# Yes, the documenttion is helpful. It clearly states the parameters and what it returns, making it easy to run and understand what is happening


help(np.append)
# Again, helpful! In addition to what I said above, the heading breakdowns help with quickly finding what you need 

Help on function transpose in module numpy:

transpose(a, axes=None)
    Permute the dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : list of ints, optional
        By default, reverse the dimensions, otherwise permute the axes
        according to the values given.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    moveaxis
    argsort
    
    Notes
    -----
    Use `transpose(a, argsort(axes))` to invert the transposition of tensors
    when using the `axes` keyword argument.
    
    Transposing a 1-D array returns an unchanged view of the original array.
    
    Examples
    --------
    >>> x = np.arange(4).reshape((2,2))
    >>> x
    array([[0, 1],
           [2, 3]])
    
    >>> np.transpose(x)
    array([[0, 2],
           [1, 3]])
    
    >>> x = np.ones((1, 2, 3))
    >>> np.transpose(x, (1, 0, 2)).s

## Task 5a: Transposing an Array

In the practice notebook perform the following:

+ Create a matrix of any size and transpose it.

In [19]:
matrix1 = np.random.random((5,4))
matrix1
matrix2 = np.transpose(matrix1)
matrix2

array([[0.38681472, 0.31180892, 0.39510983, 0.95406003, 0.84971792],
       [0.79664246, 0.17985721, 0.16222088, 0.90135132, 0.60115754],
       [0.39167685, 0.9699587 , 0.23662496, 0.83354334, 0.15983789],
       [0.07411727, 0.57767787, 0.04062585, 0.25508783, 0.01556281]])

## Task 5b: Reshaping an Array

In the practice notebook peform the following:

+ Create a matrix and resize it by adding 2 extra columns
+ Create a matrix and resize it by adding 1 extra row
+ Create a matrix of 8 x 2 and resize it to 4 x 4

In [41]:
matrix3 = np.random.random((5,3))
print(matrix3)
matrix4 = np.reshape(matrix3, (3,5))
print(matrix4)

In [41]:
matrix5 = np.random.random((10,9))
print(matrix5)
matrix6 = np.reshape(matrix5, (9,10))
print(matrix6)

In [44]:
matrix7 = np.random.random((8,2))
print(matrix7)
matrix8 = np.reshape(matrix7, (4,4))
print(matrix8)

[[0.59571176 0.10478291]
 [0.73459585 0.5264809 ]
 [0.87578547 0.4355219 ]
 [0.10183183 0.85083763]
 [0.72169681 0.80107886]
 [0.33609267 0.65396362]
 [0.0314885  0.501122  ]
 [0.46714341 0.6342036 ]]
[[0.59571176 0.10478291 0.73459585 0.5264809 ]
 [0.87578547 0.4355219  0.10183183 0.85083763]
 [0.72169681 0.80107886 0.33609267 0.65396362]
 [0.0314885  0.501122   0.46714341 0.6342036 ]]


## Task 5c: Appending to an Array

In the practice notebook perform the following:

 + Create a three dimensional array and append another row to the array
 + Append another colum to the array
 + Print the final results

In [68]:
array1 = np.random.random((4,4,4))
print(array1)

array2 = np.append(array1,[[[1,2,3,4], [2,4,6,8], [3,6,9,12], [4,8,12,16]]], axis = 0 )
print(array2)

[[[0.93360599 0.60821521 0.71213626 0.94203436]
  [0.87324288 0.52728139 0.22633228 0.85198578]
  [0.17141543 0.38422189 0.3282787  0.60179398]
  [0.64804975 0.73679587 0.81046742 0.34668508]]

 [[0.72875933 0.37764852 0.36677095 0.65594484]
  [0.55823923 0.13352    0.9313399  0.69271202]
  [0.14604084 0.36290929 0.13257114 0.15231591]
  [0.19966321 0.02454631 0.98066431 0.24251338]]

 [[0.86968076 0.74800262 0.64100655 0.46119191]
  [0.11078546 0.66572671 0.17387746 0.72450067]
  [0.82907081 0.81526119 0.10701552 0.06653028]
  [0.64121519 0.70843391 0.81970226 0.01632132]]

 [[0.19411904 0.1125397  0.039352   0.54906632]
  [0.18789519 0.80832388 0.81965209 0.62965796]
  [0.21945624 0.0471137  0.58934771 0.38938777]
  [0.81742004 0.25690731 0.12133844 0.67482702]]]
[[[ 0.93360599  0.60821521  0.71213626  0.94203436]
  [ 0.87324288  0.52728139  0.22633228  0.85198578]
  [ 0.17141543  0.38422189  0.3282787   0.60179398]
  [ 0.64804975  0.73679587  0.81046742  0.34668508]]

 [[ 0.72875933

In [73]:
finalarray = np.append(array2,[[[1,2,3,4,5], [2,4,6,8,10], [3,6,9,12,15], [4,8,12,16,20], [5,10,15,20,25]]], axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 1

## Task 5d: Inserting and Deleting Elements

In the practice notebook perform the following:

+ Examine the `help()` documentation for how to use the `insert()` and `delete()` functions.
+ Create a matrix and practice inserting a row and deleting a column.

In [78]:
help(np.insert)
help(np.delete)

matrix9 = np.random.random((4,4))
np.delete(matrix9, 1, 0)
np.insert(matrix9, 1, 4)

Help on function insert in module numpy:

insert(arr, obj, values, axis=None)
    Insert values along the given axis before the given indices.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : int, slice or sequence of ints
        Object that defines the index or indices before which `values` is
        inserted.
    
        .. versionadded:: 1.8.0
    
        Support for multiple insertions when `obj` is a single scalar or a
        sequence with one element (similar to calling insert multiple
        times).
    values : array_like
        Values to insert into `arr`. If the type of `values` is different
        from that of `arr`, `values` is converted to the type of `arr`.
        `values` should be shaped so that ``arr[...,obj,...] = values``
        is legal.
    axis : int, optional
        Axis along which to insert `values`.  If `axis` is None then `arr`
        is flattened first.
    
    Returns
    -------
    out : ndarray
        A

array([0.45096508, 4.        , 0.79433588, 0.40450015, 0.13437204,
       0.94062845, 0.57564867, 0.72499414, 0.17329933, 0.02220535,
       0.73218045, 0.84159008, 0.92833464, 0.52757522, 0.84613931,
       0.47340836, 0.23764672])

## Task 5e: Joining Arrays

In the practice notebook perform the following:

+ Execute the code (in the cell below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [79]:
# Concatentate `my_array` and `x`: similar to np.append()
my_array = np.array([1,2,3,4])
x = np.array([1,1,1,1])
print("concatenate:")
print(np.concatenate((my_array, x)))

# Stack arrays row-wise
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("\nvstack:")
print(np.vstack((my_array, my_2d_array)))

# Stack arrays horizontally
print("\nhstack:")
print(np.hstack((my_2d_array, my_2d_array)))

# Stack arrays column-wise
print("\ncolumn_stack:")
print(np.column_stack((my_2d_array, my_2d_array)))

concatenate:
[1 2 3 4 1 1 1 1]

vstack:
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]

hstack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]

column_stack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


## Task 5d: Splitting Arrays

In the practice notebook perform the following:

+ Execute the code (as shown below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [80]:
# Create a 2D array.
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("original:")
print(my_2d_array)

# Split `my_stacked_array` horizontally at the 2nd index
print("\nhsplit:")
print(np.hsplit(my_2d_array, 2))

# Split `my_stacked_array` vertically at the 2nd index
print("\nvsplit:")
print(np.vsplit(my_2d_array, 2))

original:
[[1 2 3 4]
 [5 6 7 8]]

hsplit:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

vsplit:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
